name: Build

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build jnlua jar
      run: ./gradlew build
    - name: Build natives
      run: |
        apt get install mingw-w64 build-essential gcc-multilib libc6-dev:i386
        ./build-natives-eris.sh
    - name: Upload jnlua jar
      uses: actions/upload-artifact@v3
      with:
        name: jar
        path: build/
    - name: Upload jnlua natives
      uses: actions/upload-artifact@v3
      with:
        name: native-build
        path: native-build/
